# Generated by Django 5.1.3 on 2024-12-17 22:21

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.BigIntegerField(default=1)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('coder_email', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255, null=True)),
                ('label', models.CharField(max_length=255)),
                ('notes', models.JSONField(default=dict)),
                ('due_dt', models.DateTimeField(default=api.models._two_weeks_from_now)),
                ('completed_dt', models.DateTimeField(null=True)),
                ('type', models.BigIntegerField()),
                ('status', models.CharField(default='TRIAGE', max_length=31)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.BigIntegerField(default=1)),
                ('parent', models.BigIntegerField(null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('categories', models.JSONField(default=list)),
                ('meta', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KVStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.BigIntegerField(default=1)),
                ('k', models.CharField(db_index=True, max_length=255)),
                ('v', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.BigIntegerField(default=1)),
                ('company_name', models.CharField(default=str, max_length=255)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('locale', models.CharField(max_length=32, null=True)),
                ('alexa_rank', models.BigIntegerField(null=True)),
                ('alexa_rank_US', models.BigIntegerField(null=True)),
                ('urls', models.JSONField(default=dict)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('last_scan_dt', models.DateTimeField(null=True)),
                ('scan_count', models.BigIntegerField(default=0)),
                ('categories', models.JSONField(default=list)),
                ('meta', models.JSONField(default=dict)),
                ('progress', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.BigIntegerField(default=1)),
                ('policy_id', models.BigIntegerField(db_index=True)),
                ('scan_dt', models.DateTimeField(auto_now_add=True)),
                ('content', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('settings', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.BigIntegerField(default=1)),
                ('coder_email', models.CharField(max_length=255)),
                ('coding_id', models.BigIntegerField()),
                ('policy_instance_id', models.BigIntegerField()),
                ('question_timings', models.JSONField()),
                ('session_timing', models.JSONField()),
                ('session_identifier', models.BigIntegerField(unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodingInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.BigIntegerField(default=1)),
                ('coder_email', models.CharField(db_index=True, default='unknown', max_length=255)),
                ('policy_id', models.BigIntegerField(db_index=True)),
                ('policy_instance_id', models.BigIntegerField(db_index=True)),
                ('coding_id', models.BigIntegerField(db_index=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('coding_values', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('coder_email', 'coding_id', 'policy_instance_id')},
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.BigIntegerField(default=1)),
                ('user_email', models.CharField(max_length=255)),
                ('is_owner', models.BooleanField(default=False)),
                ('can_modify_schema', models.BooleanField(default=False)),
                ('can_view_schema', models.BooleanField(default=True)),
                ('can_manage_content', models.BooleanField(default=False)),
                ('can_view_content', models.BooleanField(default=True)),
                ('can_assign_tasks', models.BooleanField(default=False)),
                ('can_view_assignments', models.BooleanField(default=True)),
                ('can_export_data', models.BooleanField(default=False)),
                ('can_review', models.BooleanField(default=False)),
                ('can_annotate', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('project', 'user_email')},
            },
        ),
    ]
