# Generated by Django 5.1.3 on 2024-12-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyinstance',
            name='scan_dt',
            field=models.DateField(),
        ),
    ]
