# Generated by Django 5.1.4 on 2024-12-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_policyinstance_scan_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='type',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='label',
            field=models.CharField(default='', max_length=255),
        ),
    ]
