# Generated by Django 5.1.4 on 2024-12-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_assignment_coder_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
