/**
 * @readonly
 * @enum {String}
 */
export const APIActionTypes = {
  GET_ASSIGNMENT_LIST: "API_GET_ASSIGNMENT_LIST",
  POST_ASSIGNMENT: "API_POST_ASSIGNMENT",
  UPDATE_ASSIGNMENT: "API_UPDATE_ASSIGNMENT",
  GET_PROJECT_SETTINGS: "GET_PROJECT_SETTINGS",
  GET_PROJECT_LIST: "API_GET_PROJECT_LIST",
  GET_POLICY: "API_GET_POLICY",
  GET_POLICIES: "API_GET_POLICIES",
  GET_POLICY_INSTANCE: "API_GET_POLICY_INSTANCE",
  GET_POLICY_INSTANCES: "API_GET_POLICY_INSTANCES",
  GET_REPORT: "API_GET_REPORT",
  POST_POLICY: "API_POST_POLICY",
  POST_POLICY_INSTANCE: "API_POST_POLICY_INSTANCE",
  POST_POLICY_INSTANCE_DOCUMENT: "API_POST_POLICY_INSTANCE_DOCUMENT",
  POST_PROJECT_ROLE: "API_POST_PROJECT_ROLE",
  GET_POLICY_INSTANCE_META: "API_GET_POLICY_INSTANCE_META",
  GET_PROJECT_ROLES: "API_GET_PROJECT_ROLES",
  GET_CODING: "API_GET_CODING",
  GET_CODING_LIST: "API_GET_CODING_LIST",
  GET_CODING_PROGRESS: "API_GET_CODING_PROGRESS",
  POST_CODING_INSTANCE: "API_POST_CODING_INSTANCE",
  GET_CODING_INSTANCE: "API_GET_CODING_INSTANCE",
  AUTO_SAVE: "API_AUTO_SAVE",
  GET_ALL_CODING_INSTANCE: "API_GET_ALL_CODING_INSTANCE",
  ERROR: "ERROR",
  SERVER_CODING_INSTANCE: "SERVER_CODING_INSTANCE",
};

export const APIStatusActionTypes = {
  START: "API_START",
  SUCCESS: "API_SUCCESS",
  ERROR: "API_ERROR",
};

/**
 * @readonly
 * @enum {String}
 */
export const UserActionsTypes = {
  UPDATE_CODING: "UPDATE_CODING",
  SELECT_QUESTION: "USER_SELECT_QUESTION",
  CHANGE_VALUE: "USER_CHANGE_VALUE",
  TOGGLE_SENTENCE: "USER_TOGGLE_SENTENCE",
  TOGGLE_PARAGRAPH: "USER_TOGGLE_PARAGRAPH",
  CLICK_SAVE: "USER_CLICK_SAVE",
  CLICK_RESET: "USER_CLICK_RESET",
  CHANGE_QUESTION_META: "USER_CHANGE_QUESTION_META",
};
/**
 * @readonly
 * @enum {String}
 */
export const AppActionTypes = {
  SET_CURRENT_VIEW: "APP_SET_CURRENT_VIEW",
  SET_CODING_MODE: "APP_SET_MODE",
};
/**
 * @readonly
 * @enum {String}
 */
export const NULL_OP = "NULL_OP";
